[discord]
client_id = "..." # Your Discord client ID used for Oauth2
client_secret = "..." # Your Discord client secret used for Oauth2

[encryption]
token_encryption_key = "..." # HEX encoded AES key for encrypting Discord tokens
